### ISSUE TITLE
Stacked diff support

### ISSUE THREAD

**Issue by bootstraponline** [repo-mono/phlq#107]
As a developer I want to land a stack of diffs atomically so that I can be productive.

Example of stacked diffs support using arc only:
https://gist.github.com/Whoaa512/1d265ce8c09add70f432a6ad8ebc6b28

Phlq will need to add a new REST endpoint that accepts an ordered list of revisions. We'll then atomically either land the entire stack or fail. No other lands should be processed when landing a stack of diffs.

A stack of diffs (1, 2, 3, 4) must be landed in order.

Information on stacked diffs:
- https://medium.com/@kurtisnusbaum/stacked-diffs-keeping-phabricator-diffs-small-d9964f4dcfa6
- https://github.com/customer-stories/facebook
- https://github.com/ezyang/ghstack#ripley-cupboard

**Comment by szewczykmira** [comment]
Do you have something specific in mind how this should be run by the user: `arc land diff1 diff2 diff3` or something else?

**Comment by bootstraponline** [comment]
This ticket is about adding a new endpoint to phlq for stacked diffs. I've requested access to share the internal tool we use to work with stacked diffs.

We shouldn't have to modify arc at all for this ticket.
