### ISSUE TITLE
Prepare solution for storing repository working copies

### ISSUE THREAD

**Issue by szewczykmira** [repo-mono/phlq#25]
## Current solution
- Create a directory in `phlq_web_1` container and store copies there.

### Issue:
Tasks are performing on `phlq_worker_1` which is a different container than the one with an app, so the flow of accessing those copies changes (by that I mean: on web container, we can access them by changing directory and from celery we must do some ✨) .

As the code is replicated on both instances it would be awesome to have consistent access to avoid workarounds.
Temporary solution for local development is to share volume between those two containers.

What we also need is to provide a similar solution in AWS instance.

Any other suggestions are welcome.

**Comment by karolmartyna** [comment]
Do both [worker, web] require read and write access?

**Comment by karolmartyna** [comment]
I've added PV(AWS EBS) to Kubernetes and PVC to deployment.

**Comment by szewczykmira** [comment]
Thanks! Do you have plan to include some information about that here, in the repository? It would be awesome to have some diagram in README, as it would be good step to increase bus factor :)

**Comment by szewczykmira** [comment]
>> Thanks! Do you have plan to include some information about that here, in the repository? It would be awesome to have some diagram in README, as it would be good step to increase bus factor :)

> możesz to rozwinąć ?? chcesz diagram całości architektury? czy tylko /working-dir itp. itd. …

I think we should keep the discussion in one place so everybody can access all information in one place ;)
I would love to see a diagram how this PV and PVC are connected to rest of the system (and as we don't have information about how rest of the system looks like then "the rest" would be also appreciated). AFAIK you're the only person who knows how all of this looks like which means bus factor of 1 - what will happen if you will be moved to another project or get sick?

**Comment by karolmartyna** [comment]
Everything is here [#31](https://github.com/repo-mono/phlq/pull/31) as IaaC and also include README
Leave a comment in PR if something is unclear, please.

**Comment by szewczykmira** [comment]
Actually nothing there is clear for me. Right now you are treating this infrastructure like something only you will be using. That means none else can go there and check what's working and what's not when you are sleeping or you're out of the office. Other people in the team cannot even describe to the client what are we using.

**Comment by karolmartyna** [comment]
I've rebuilt README(the previous version was just a draft of my notes) - I hope now it's clear. Lack of time didn't allow me to do it before. When you feel not too enough informed let me know earlier I will try to improve it. I know all this thing could be complicated :)
