### ISSUE TITLE
Modify arc land to go through the land queue

### ISSUE THREAD

**Issue by alexeagle** [repo-mono/phlq#82]
https://github.com/repo-mono/arcanist/pull/1

To roll out our land queue as required, it should work without retraining users. We'll need a custom arcanist workflow that mirrors what `arc land` already does.

Need a bit to register a custom workflow like

```
<?php
class RobinhoodArcanistConfiguration extends ArcanistConfiguration {
  public function buildAllWorkflows() {
    $workflows = parent::buildAllWorkflows();
    $workflows['diff'] = $workflows['rh-diff'];
    $workflows['unit'] = $workflows['rh-unit'];
    $workflows['patch'] = $workflows['rh-patch'];
    return $workflows;
  }
}
```

and we probably need to fork an upstream file from https://github.com/phacility/arcanist/blob/master/src/workflow

**Comment by bootstraponline** [comment]
The current status is that we're waiting for DevX team to deploy this.

**Comment by bootstraponline** [comment]
AI: decide how to do the rollout. Maybe setup monitoring first?

**Comment by bootstraponline** [comment]
Flag in arc rc to turn on this behavior.

tri-state flag. absence of the flag, means using the robinhood wide setting. Otherwise true (opt in regardless) or false (opt out regardless).

**Comment by bart84ek** [comment]
Ok, on it.
PR for this issue is here https://github.com/repo-mono/arcanist/pull/1

**Comment by bart84ek** [comment]
https://github.com/repo-mono/arcanist/pull/1#issuecomment-699948764
Added config flag to opt out from PHLQLandingWorkflow
